### ISSUE TITLE
Missing edit function for courses

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#69] opened 2020-08-21 12:18 UTC
Currently, there is no edit function for courses. It seems to have disappeared by accident.

**Comment by geroembser** [comment] 2020-08-28 21:31
For me editing basically works. But I think the problem is that it does not work under the originally specified constraints (https://github.com/corona-school/project-user/issues/33). So as long as the course is not submitted, it can be edited. 

### What needs to be added: 
- [ ]  allow editing after the course was accepted: 
    - [ ] allow to edit full description 
    - [ ] allow to add further dates 48 hours in advance
    - [ ] prevent modifications and deletions of existing dates


### Open question: 
What happens if the course is submitted, but not yet accepted or rejected? Should it be editable as it was accepted? Or as it wasn't submitted? Or should editing be disallowed until it is accepted?

**Comment by tobiasbork** [comment] 2020-11-08 10:11
Until the course was accepted including the time after submission and possible rejection states, the entire course should be editable. 
After accepting only the following properties should be editable:
- [ ] allow to edit full description
- [ ]  allow to add further dates 48 hours in advance
- [ ]  prevent modifications and deletions of existing dates

**Comment by geroembser** [comment] 2021-01-31 03:42
This will no longer be worked on because it is obsolete. This one will be closed in favor of https://github.com/corona-school/project-user/issues/227

**Closed by geroembser** 2021-01-31 03:42 UTC
Labels: bug, topic:courses, wontfix
