### ISSUE TITLE
Do not display logout button

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#44] opened 2020-07-16 10:59 UTC
Users seem to have massive problems when trying to login an do not understand our system. Hence, the logout button should be hidden or deleted completely to prevent users from logging out.

**Comment by LeonErath** [comment] 2020-08-16 08:25
@tobiasbork  Should this still be done? Could imagine that there are situations where I want to log out. Maybe it helps to just move the button to the "Verwaltung" tab so that it cannot be found that quickly. Otherwise I'll throw it out afterwards.

**Comment by geroembser** [comment] 2020-08-28 22:10
So that we don't lose sight of this topic, I will give the whole thing a little more activity by adding my comment.

In my opinion this is a good idea. As @LeonErath already said, we can always throw it out later. Another way I could imagine is somehow clicking on the user's avatar or name in the side nav. This could open a dropdown with an option to log out. 

What do you think @tobiasbork?

**Comment by realmayus** [comment] 2021-01-09 11:41
Duplicate of https://github.com/corona-school/project-user/issues/231, which was closed recently.

**Closed by realmayus** 2021-01-09 11:41 UTC
Labels: enhancement
