### ISSUE TITLE
Course cannot see detailed view

### ISSUE THREAD

**Issue by tobiasbork** [corona-school/web-user-app#27] opened 2020-07-07 17:45 UTC
Currently, I cannot access the detailed view of a course unless I am the creator of the course. Tutor and tutess should both be able to access the detailed view of the course.
![image](https://user-images.githubusercontent.com/39235832/86821058-35de4380-c08a-11ea-8d68-580abfbc5c3c.png)
![image](https://user-images.githubusercontent.com/39235832/86821127-47275000-c08a-11ea-972e-55ef79c57482.png)

**Comment by LeonErath** [comment] 2020-07-07 18:22
The message "Wir konnten den Kurs leider nicht finden." only comes if the course is not found by the API or has no subcourse. In general, a tutee and a tutor can view the course detail page. The database states that the courses have not yet been published and are therefore not being viewed by others. The bug here is that unpublished courses still appear in "All courses".

**Comment by geroembser** [comment] 2020-07-23 09:42
Should be fixed since every submitted course automatically gets published (i.e. with 53571162). Otherwise please reopen with detailed information on how to reproduce the issues.

**Closed by geroembser** 2020-07-23 09:42 UTC
Labels: bug, topic:courses
